pipeline {
    // master executor should be set to 0
    agent any
    stages {
    	stage("Start Pull Latest Image"){
    		steps {
    	     	bat "docker pull ahmedhakem/cucumber-docker:cucumber-docker"
    	    }	
    	}
    	stage("Start Grid"){
    	     steps {
    	     	bat "docker-compose up -d hub firefox edge chrome"
    	    }
    	}
    	stage("Run Tests"){
    	     steps {
    	     	bat "docker-compose up testng-module"
    	    }
    	}
    }
    post {
        always {
            cucumber buildStatus: 'null', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: 0, failedScenariosNumber: 0, failedStepsNumber: 0, fileIncludePattern: '**/*.json', jsonReportDirectory: '', pendingStepsNumber: 0, skippedStepsNumber: 0, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: 0
            bat "docker-compose down"
            script {
            currentBuild.result = checkTestResult()
            if (currentBuild.result == 'FAILURE') {
                sh "exit 1"
        }
        }
    }
}
