pipeline {
    // master executor should be set to 0
    agent any
    stages {
    	stage("Start Pull Latest Image"){
    		steps {
    	     	bat "docker pull ahmedhakem/cucumber-docker:cucumber-docker"
    	    }	
    	}
    	stage("Start Grid"){
    	     steps {
    	     	bat "docker-compose up -d hub firefox edge chrome"
    	    }
    	}
    	stage("Run Tests"){
    	     steps {
    	     	bat "docker-compose up testng-module"
    	    }
    	}
    }
    post {
        always {
            cucumber buildStatus: 'UNSTABLE',
                            failedFeaturesNumber: 1,
                            failedScenariosNumber: 1,
                            skippedStepsNumber: 1,
                            failedStepsNumber: 1,
                            classifications: [
                                    [key: 'Commit', value: '<a href="${GERRIT_CHANGE_URL}">${GERRIT_PATCHSET_REVISION}</a>'],
                                    [key: 'Submitter', value: '${GERRIT_PATCHSET_UPLOADER_NAME}']
                            ],
                            reportTitle: 'My report',
                            fileIncludePattern: '**/*cucumber.json',
                            sortingMethod: 'ALPHABETICAL',
                            trendsLimit: 100
            bat "docker-compose down"
        }
    }
}
